[project]
name = "agentic-quant"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "numpy>=1.26",
  "numba>=0.59",
  "polars>=0.20",
  "typer>=0.12",
  "lark>=1.1",
  "jinja2>=3.1",
  "requests>=2.32",
]
